databases:
  postgres:
    host: postgres
    port: 5432
    user: postgres
    password: postgres
    dbname: postgres

  mariadb:
    host: mariadb
    port: 3306
    user: root
    password: root
    dbname: mysql

  neo4j:
    host: neo4j
    port: 7687
    user: neo4j
    password: password

  mongodb:
    host: mongodb
    port: 27017
    dbname: test

  clickhouse:
    host: clickhouse
    port: 9000
    user: default
    password: ""
    dbname: default